// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'emission_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EmissionData _$EmissionDataFromJson(Map<String, dynamic> json) => EmissionData(
      (json['alcDrinks'] as num?)?.toDouble(),
      (json['animalCheese'] as num?)?.toDouble(),
      (json['animalCream'] as num?)?.toDouble(),
      (json['animalDeli'] as num?)?.toDouble(),
      (json['animalJogurt'] as num?)?.toDouble(),
      (json['animalMilk'] as num?)?.toDouble(),
      (json['beef'] as num?)?.toDouble(),
      (json['bread'] as num?)?.toDouble(),
      (json['butter'] as num?)?.toDouble(),
      (json['cereal'] as num?)?.toDouble(),
      (json['eggs'] as num?)?.toDouble(),
      (json['fish'] as num?)?.toDouble(),
      (json['fruits'] as num?)?.toDouble(),
      (json['legumes'] as num?)?.toDouble(),
      (json['margarine'] as num?)?.toDouble(),
      (json['meatSubstitutes'] as num?)?.toDouble(),
      (json['nuts'] as num?)?.toDouble(),
      (json['pasta'] as num?)?.toDouble(),
      (json['plantCheese'] as num?)?.toDouble(),
      (json['plantCream'] as num?)?.toDouble(),
      (json['plantDeli'] as num?)?.toDouble(),
      (json['plantJogurt'] as num?)?.toDouble(),
      (json['plantMilk'] as num?)?.toDouble(),
      (json['pork'] as num?)?.toDouble(),
      (json['potatoes'] as num?)?.toDouble(),
      (json['poultry'] as num?)?.toDouble(),
      (json['rice'] as num?)?.toDouble(),
      (json['saltySnacks'] as num?)?.toDouble(),
      (json['sausages'] as num?)?.toDouble(),
      (json['spread'] as num?)?.toDouble(),
      (json['tea'] as num?)?.toDouble(),
      (json['tofu'] as num?)?.toDouble(),
      (json['vegetables'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$EmissionDataToJson(EmissionData instance) =>
    <String, dynamic>{
      'alcDrinks': instance.alcDrinks,
      'animalCheese': instance.animalCheese,
      'animalCream': instance.animalCream,
      'animalDeli': instance.animalDeli,
      'animalJogurt': instance.animalJogurt,
      'animalMilk': instance.animalMilk,
      'beef': instance.beef,
      'bread': instance.bread,
      'butter': instance.butter,
      'cereal': instance.cereal,
      'eggs': instance.eggs,
      'fish': instance.fish,
      'fruits': instance.fruits,
      'legumes': instance.legumes,
      'margarine': instance.margarine,
      'meatSubstitutes': instance.meatSubstitutes,
      'nuts': instance.nuts,
      'pasta': instance.pasta,
      'plantCheese': instance.plantCheese,
      'plantCream': instance.plantCream,
      'plantDeli': instance.plantDeli,
      'plantJogurt': instance.plantJogurt,
      'plantMilk': instance.plantMilk,
      'pork': instance.pork,
      'potatoes': instance.potatoes,
      'poultry': instance.poultry,
      'rice': instance.rice,
      'saltySnacks': instance.saltySnacks,
      'sausages': instance.sausages,
      'spread': instance.spread,
      'tea': instance.tea,
      'tofu': instance.tofu,
      'vegetables': instance.vegetables,
    };
