// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'survey_answers_pre_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SurveyAnswersPreData _$SurveyAnswersPreDataFromJson(
        Map<String, dynamic> json) =>
    SurveyAnswersPreData(
      json['date'] as String?,
      (json['alcDrinks'] as num?)?.toDouble(),
      (json['animalCheese'] as num?)?.toDouble(),
      (json['animalCream'] as num?)?.toDouble(),
      (json['animalDeli'] as num?)?.toDouble(),
      (json['animalJogurt'] as num?)?.toDouble(),
      (json['animalMilk'] as num?)?.toDouble(),
      (json['beef'] as num?)?.toDouble(),
      (json['bread'] as num?)?.toDouble(),
      (json['butter'] as num?)?.toDouble(),
      (json['cereal'] as num?)?.toDouble(),
      (json['eggs'] as num?)?.toDouble(),
      (json['fish'] as num?)?.toDouble(),
      (json['fruits'] as num?)?.toDouble(),
      (json['legumes'] as num?)?.toDouble(),
      (json['margarine'] as num?)?.toDouble(),
      (json['meatSubstitutes'] as num?)?.toDouble(),
      (json['nuts'] as num?)?.toDouble(),
      (json['pasta'] as num?)?.toDouble(),
      (json['plantCheese'] as num?)?.toDouble(),
      (json['plantCream'] as num?)?.toDouble(),
      (json['plantDeli'] as num?)?.toDouble(),
      (json['plantJogurt'] as num?)?.toDouble(),
      (json['plantMilk'] as num?)?.toDouble(),
      (json['pork'] as num?)?.toDouble(),
      (json['potatoes'] as num?)?.toDouble(),
      (json['poultry'] as num?)?.toDouble(),
      (json['rice'] as num?)?.toDouble(),
      (json['saltySnacks'] as num?)?.toDouble(),
      (json['sausages'] as num?)?.toDouble(),
      (json['spread'] as num?)?.toDouble(),
      (json['tea'] as num?)?.toDouble(),
      (json['tofu'] as num?)?.toDouble(),
      (json['vegetables'] as num?)?.toDouble(),
      (json['alcDrinksKG'] as num?)?.toDouble(),
      (json['animalCheeseKG'] as num?)?.toDouble(),
      (json['animalCreamKG'] as num?)?.toDouble(),
      (json['animalDeliKG'] as num?)?.toDouble(),
      (json['animalJogurtKG'] as num?)?.toDouble(),
      (json['animalMilkKG'] as num?)?.toDouble(),
      (json['beefKG'] as num?)?.toDouble(),
      (json['breadKG'] as num?)?.toDouble(),
      (json['butterKG'] as num?)?.toDouble(),
      (json['cerealKG'] as num?)?.toDouble(),
      (json['eggsKG'] as num?)?.toDouble(),
      (json['fishKG'] as num?)?.toDouble(),
      (json['fruitsKG'] as num?)?.toDouble(),
      (json['legumesKG'] as num?)?.toDouble(),
      (json['margarineKG'] as num?)?.toDouble(),
      (json['meatSubstitutesKG'] as num?)?.toDouble(),
      (json['nutsKG'] as num?)?.toDouble(),
      (json['pastaKG'] as num?)?.toDouble(),
      (json['plantCheeseKG'] as num?)?.toDouble(),
      (json['plantCreamKG'] as num?)?.toDouble(),
      (json['plantDeliKG'] as num?)?.toDouble(),
      (json['plantJogurtKG'] as num?)?.toDouble(),
      (json['plantMilkKG'] as num?)?.toDouble(),
      (json['porkKG'] as num?)?.toDouble(),
      (json['potatoesKG'] as num?)?.toDouble(),
      (json['poultryKG'] as num?)?.toDouble(),
      (json['riceKG'] as num?)?.toDouble(),
      (json['saltySnacksKG'] as num?)?.toDouble(),
      (json['sausagesKG'] as num?)?.toDouble(),
      (json['spreadKG'] as num?)?.toDouble(),
      (json['teaKG'] as num?)?.toDouble(),
      (json['tofuKG'] as num?)?.toDouble(),
      (json['vegetablesKG'] as num?)?.toDouble(),
      (json['alcDrinksCO2'] as num?)?.toDouble(),
      (json['animalCheeseCO2'] as num?)?.toDouble(),
      (json['animalCreamCO2'] as num?)?.toDouble(),
      (json['animalDeliCO2'] as num?)?.toDouble(),
      (json['animalJogurtCO2'] as num?)?.toDouble(),
      (json['animalMilkCO2'] as num?)?.toDouble(),
      (json['beefCO2'] as num?)?.toDouble(),
      (json['breadCO2'] as num?)?.toDouble(),
      (json['butterCO2'] as num?)?.toDouble(),
      (json['cerealCO2'] as num?)?.toDouble(),
      (json['eggsCO2'] as num?)?.toDouble(),
      (json['fishCO2'] as num?)?.toDouble(),
      (json['fruitsCO2'] as num?)?.toDouble(),
      (json['legumesCO2'] as num?)?.toDouble(),
      (json['margarineCO2'] as num?)?.toDouble(),
      (json['meatSubstitutesCO2'] as num?)?.toDouble(),
      (json['nutsCO2'] as num?)?.toDouble(),
      (json['pastaCO2'] as num?)?.toDouble(),
      (json['plantCheeseCO2'] as num?)?.toDouble(),
      (json['plantCreamCO2'] as num?)?.toDouble(),
      (json['plantDeliCO2'] as num?)?.toDouble(),
      (json['plantJogurtCO2'] as num?)?.toDouble(),
      (json['plantMilkCO2'] as num?)?.toDouble(),
      (json['porkCO2'] as num?)?.toDouble(),
      (json['potatoesCO2'] as num?)?.toDouble(),
      (json['poultryCO2'] as num?)?.toDouble(),
      (json['riceCO2'] as num?)?.toDouble(),
      (json['saltySnacksCO2'] as num?)?.toDouble(),
      (json['sausagesCO2'] as num?)?.toDouble(),
      (json['spreadCO2'] as num?)?.toDouble(),
      (json['teaCO2'] as num?)?.toDouble(),
      (json['tofuCO2'] as num?)?.toDouble(),
      (json['vegetablesCO2'] as num?)?.toDouble(),
      (json['freeDrinks'] as num?)?.toDouble(),
      (json['freeDrinksKG'] as num?)?.toDouble(),
      (json['freeDrinksCO2'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$SurveyAnswersPreDataToJson(
        SurveyAnswersPreData instance) =>
    <String, dynamic>{
      'date': instance.date,
      'alcDrinks': instance.alcDrinks,
      'animalCheese': instance.animalCheese,
      'animalCream': instance.animalCream,
      'animalDeli': instance.animalDeli,
      'animalJogurt': instance.animalJogurt,
      'animalMilk': instance.animalMilk,
      'beef': instance.beef,
      'bread': instance.bread,
      'butter': instance.butter,
      'cereal': instance.cereal,
      'eggs': instance.eggs,
      'fish': instance.fish,
      'freeDrinks': instance.freeDrinks,
      'fruits': instance.fruits,
      'legumes': instance.legumes,
      'margarine': instance.margarine,
      'meatSubstitutes': instance.meatSubstitutes,
      'nuts': instance.nuts,
      'pasta': instance.pasta,
      'plantCheese': instance.plantCheese,
      'plantCream': instance.plantCream,
      'plantDeli': instance.plantDeli,
      'plantJogurt': instance.plantJogurt,
      'plantMilk': instance.plantMilk,
      'pork': instance.pork,
      'potatoes': instance.potatoes,
      'poultry': instance.poultry,
      'rice': instance.rice,
      'saltySnacks': instance.saltySnacks,
      'sausages': instance.sausages,
      'spread': instance.spread,
      'tea': instance.tea,
      'tofu': instance.tofu,
      'vegetables': instance.vegetables,
      'alcDrinksKG': instance.alcDrinksKG,
      'animalCheeseKG': instance.animalCheeseKG,
      'animalCreamKG': instance.animalCreamKG,
      'animalDeliKG': instance.animalDeliKG,
      'animalJogurtKG': instance.animalJogurtKG,
      'animalMilkKG': instance.animalMilkKG,
      'beefKG': instance.beefKG,
      'breadKG': instance.breadKG,
      'butterKG': instance.butterKG,
      'cerealKG': instance.cerealKG,
      'eggsKG': instance.eggsKG,
      'fishKG': instance.fishKG,
      'freeDrinksKG': instance.freeDrinksKG,
      'fruitsKG': instance.fruitsKG,
      'legumesKG': instance.legumesKG,
      'margarineKG': instance.margarineKG,
      'meatSubstitutesKG': instance.meatSubstitutesKG,
      'nutsKG': instance.nutsKG,
      'pastaKG': instance.pastaKG,
      'plantCheeseKG': instance.plantCheeseKG,
      'plantCreamKG': instance.plantCreamKG,
      'plantDeliKG': instance.plantDeliKG,
      'plantJogurtKG': instance.plantJogurtKG,
      'plantMilkKG': instance.plantMilkKG,
      'porkKG': instance.porkKG,
      'potatoesKG': instance.potatoesKG,
      'poultryKG': instance.poultryKG,
      'riceKG': instance.riceKG,
      'saltySnacksKG': instance.saltySnacksKG,
      'sausagesKG': instance.sausagesKG,
      'spreadKG': instance.spreadKG,
      'teaKG': instance.teaKG,
      'tofuKG': instance.tofuKG,
      'vegetablesKG': instance.vegetablesKG,
      'alcDrinksCO2': instance.alcDrinksCO2,
      'animalCheeseCO2': instance.animalCheeseCO2,
      'animalCreamCO2': instance.animalCreamCO2,
      'animalDeliCO2': instance.animalDeliCO2,
      'animalJogurtCO2': instance.animalJogurtCO2,
      'animalMilkCO2': instance.animalMilkCO2,
      'beefCO2': instance.beefCO2,
      'breadCO2': instance.breadCO2,
      'butterCO2': instance.butterCO2,
      'cerealCO2': instance.cerealCO2,
      'eggsCO2': instance.eggsCO2,
      'fishCO2': instance.fishCO2,
      'freeDrinksCO2': instance.freeDrinksCO2,
      'fruitsCO2': instance.fruitsCO2,
      'legumesCO2': instance.legumesCO2,
      'margarineCO2': instance.margarineCO2,
      'meatSubstitutesCO2': instance.meatSubstitutesCO2,
      'nutsCO2': instance.nutsCO2,
      'pastaCO2': instance.pastaCO2,
      'plantCheeseCO2': instance.plantCheeseCO2,
      'plantCreamCO2': instance.plantCreamCO2,
      'plantDeliCO2': instance.plantDeliCO2,
      'plantJogurtCO2': instance.plantJogurtCO2,
      'plantMilkCO2': instance.plantMilkCO2,
      'porkCO2': instance.porkCO2,
      'potatoesCO2': instance.potatoesCO2,
      'poultryCO2': instance.poultryCO2,
      'riceCO2': instance.riceCO2,
      'saltySnacksCO2': instance.saltySnacksCO2,
      'sausagesCO2': instance.sausagesCO2,
      'spreadCO2': instance.spreadCO2,
      'teaCO2': instance.teaCO2,
      'tofuCO2': instance.tofuCO2,
      'vegetablesCO2': instance.vegetablesCO2,
    };
