import 'package:json_annotation/json_annotation.dart';

part 'survey_answers_pre_data.g.dart';

@JsonSerializable()
class SurveyAnswersPreData {
  final String? date;
  final double? alcDrinks,
      animalCheese,
      animalCream,
      animalDeli,
      animalJogurt,
      animalMilk,
      beef,
      bread,
      butter,
      cereal,
      eggs,
      fish,
      freeDrinks,
      fruits,
      legumes,
      margarine,
      meatSubstitutes,
      nuts,
      pasta,
      plantCheese,
      plantCream,
      plantDeli,
      plantJogurt,
      plantMilk,
      pork,
      potatoes,
      poultry,
      rice,
      saltySnacks,
      sausages,
      spread,
      tea,
      tofu,
      vegetables,
      alcDrinksKG,
      animalCheeseKG,
      animalCreamKG,
      animalDeliKG,
      animalJogurtKG,
      animalMilkKG,
      beefKG,
      breadKG,
      butterKG,
      cerealKG,
      eggsKG,
      fishKG,
      freeDrinksKG,
      fruitsKG,
      legumesKG,
      margarineKG,
      meatSubstitutesKG,
      nutsKG,
      pastaKG,
      plantCheeseKG,
      plantCreamKG,
      plantDeliKG,
      plantJogurtKG,
      plantMilkKG,
      porkKG,
      potatoesKG,
      poultryKG,
      riceKG,
      saltySnacksKG,
      sausagesKG,
      spreadKG,
      teaKG,
      tofuKG,
      vegetablesKG, 
      alcDrinksCO2,
      animalCheeseCO2,
      animalCreamCO2,
      animalDeliCO2,
      animalJogurtCO2,
      animalMilkCO2,
      beefCO2,
      breadCO2,
      butterCO2,
      cerealCO2,
      eggsCO2,
      fishCO2,
      freeDrinksCO2,
      fruitsCO2,
      legumesCO2,
      margarineCO2,
      meatSubstitutesCO2,
      nutsCO2,
      pastaCO2,
      plantCheeseCO2,
      plantCreamCO2,
      plantDeliCO2,
      plantJogurtCO2,
      plantMilkCO2,
      porkCO2,
      potatoesCO2,
      poultryCO2,
      riceCO2,
      saltySnacksCO2,
      sausagesCO2,
      spreadCO2,
      teaCO2,
      tofuCO2,
      vegetablesCO2;

  SurveyAnswersPreData(this.date, this.alcDrinks, this.animalCheese, this.animalCream, this.animalDeli, this.animalJogurt, this.animalMilk, this.beef, this.bread, this.butter, this.cereal, this.eggs, this.fish, this.fruits, this.legumes, this.margarine, this.meatSubstitutes, this.nuts, this.pasta, this.plantCheese, this.plantCream, this.plantDeli, this.plantJogurt, this.plantMilk, this.pork, this.potatoes, this.poultry, this.rice, this.saltySnacks, this.sausages, this.spread, this.tea, this.tofu, this.vegetables, this.alcDrinksKG, this.animalCheeseKG, this.animalCreamKG, this.animalDeliKG, this.animalJogurtKG, this.animalMilkKG, this.beefKG, this.breadKG, this.butterKG, this.cerealKG, this.eggsKG, this.fishKG, this.fruitsKG, this.legumesKG, this.margarineKG, this.meatSubstitutesKG, this.nutsKG, this.pastaKG, this.plantCheeseKG, this.plantCreamKG, this.plantDeliKG, this.plantJogurtKG, this.plantMilkKG, this.porkKG, this.potatoesKG, this.poultryKG, this.riceKG, this.saltySnacksKG, this.sausagesKG, this.spreadKG, this.teaKG, this.tofuKG, this.vegetablesKG, this.alcDrinksCO2, this.animalCheeseCO2, this.animalCreamCO2, this.animalDeliCO2, this.animalJogurtCO2, this.animalMilkCO2, this.beefCO2, this.breadCO2, this.butterCO2, this.cerealCO2, this.eggsCO2, this.fishCO2, this.fruitsCO2, this.legumesCO2, this.margarineCO2, this.meatSubstitutesCO2, this.nutsCO2, this.pastaCO2, this.plantCheeseCO2, this.plantCreamCO2, this.plantDeliCO2, this.plantJogurtCO2, this.plantMilkCO2, this.porkCO2, this.potatoesCO2, this.poultryCO2, this.riceCO2, this.saltySnacksCO2, this.sausagesCO2, this.spreadCO2, this.teaCO2, this.tofuCO2, this.vegetablesCO2, this.freeDrinks, this.freeDrinksKG, this.freeDrinksCO2
      );

  factory SurveyAnswersPreData.fromJson(Map<String, dynamic> json) =>
      _$SurveyAnswersPreDataFromJson(json);

  Map<String, dynamic> toJson() => _$SurveyAnswersPreDataToJson(this);
}
